In [22]:
import pandas as pd
import numpy as np

In [23]:
data = pd.read_csv('iris.csv')
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [24]:
data.shape

(150, 6)

In [25]:
data['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [27]:
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [28]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [29]:
x = data.iloc[:, 1:5]
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [30]:
y = data.iloc[:, -1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [31]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)
x[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [33]:
x_train.shape

(120, 4)

In [34]:
x_test.shape

(30, 4)

### Train model using KNN

In [35]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [36]:
pred = model.predict(x_test)
pred[0:5]

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa'], dtype=object)

In [37]:
y_test[0:5]

79     Iris-versicolor
65     Iris-versicolor
138     Iris-virginica
146     Iris-virginica
44         Iris-setosa
Name: Species, dtype: object

#### Check the accuracy of the modeel

In [39]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, pred)
accuracy

0.9333333333333333

In [40]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred)
cm

array([[11,  0,  0],
       [ 0,  9,  1],
       [ 0,  1,  8]])

In [41]:
result = pd.DataFrame(data=[y_test.values, pred], index=['y_test', 'pred'])
result.transpose()

y_test             pred
0   Iris-versicolor  Iris-versicolor
1   Iris-versicolor  Iris-versicolor
2    Iris-virginica   Iris-virginica
3    Iris-virginica   Iris-virginica
4       Iris-setosa      Iris-setosa
5    Iris-virginica  Iris-versicolor
6   Iris-versicolor  Iris-versicolor
7   Iris-versicolor   Iris-virginica
8    Iris-virginica   Iris-virginica
9   Iris-versicolor  Iris-versicolor
10      Iris-setosa      Iris-setosa
11      Iris-setosa      Iris-setosa
12      Iris-setosa      Iris-setosa
13  Iris-versicolor  Iris-versicolor
14      Iris-setosa      Iris-setosa
15  Iris-versicolor  Iris-versicolor
16   Iris-virginica   Iris-virginica
17  Iris-versicolor  Iris-versicolor
18      Iris-setosa      Iris-setosa
19   Iris-virginica   Iris-virginica
20      Iris-setosa      Iris-setosa
21  Iris-versicolor  Iris-versicolor
22      Iris-setosa      Iris-setosa
23   Iris-virginica   Iris-virginica
24      Iris-setosa      Iris-setosa
25   Iris-virginica   Iris-virginica
26      Iris-setosa      Iris-setosa
27      Iris-setosa      Iris-setosa
28  Iris-versicolor  Iris-versicolor
29   Iris-virginica   Iris-virginica

In [42]:
correct_sum = []

for i in range(1,20):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train, y_train)
    pred = model.predict(x_test)
    accuracy = accuracy_score(y_test, pred)
    correct_sum.append(accuracy)

In [43]:
correct_sum

[0.9333333333333333,
 0.9666666666666667,
 0.9666666666666667,
 0.9333333333333333,
 0.9333333333333333,
 0.9333333333333333,
 0.9666666666666667,
 0.9666666666666667,
 0.9666666666666667,
 0.9333333333333333,
 0.9666666666666667,
 0.9333333333333333,
 1.0,
 0.9666666666666667,
 1.0,
 1.0,
 1.0,
 0.9666666666666667,
 0.9666666666666667]

In [44]:
result = pd.DataFrame(data=correct_sum)
result.index = result.index+1
result.T

1         2         3         4         5         6         7   \
0  0.933333  0.966667  0.966667  0.933333  0.933333  0.933333  0.966667   

         8         9         10        11        12   13        14   15   16  \
0  0.966667  0.966667  0.933333  0.966667  0.933333  1.0  0.966667  1.0  1.0   

    17        18        19  
0  1.0  0.966667  0.966667

In [45]:
model = KNeighborsClassifier(n_neighbors=13)
model.fit(x_train, y_train)
pred = model.predict(x_test)
accuracy = accuracy_score(y_test, pred)
accuracy

1.0

In [46]:
confusion_matrix(y_test, pred)

array([[11,  0,  0],
       [ 0, 10,  0],
       [ 0,  0,  9]])